version: '3'
services:

  #PHP Service
  app:
    build: .
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "8181:8181"
    networks:
      - app-network

  db:
    image: mysql:5.7.25
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: imanager
      MYSQL_ROOT_PASSWORD: strong
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
